project:
  type: website
  output-dir: docs

website:
  title: "SNGKEL002.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Write-Up
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



